### ISSUE TITLE
How to only use posframe for particular vertico commands?

### ISSUE THREAD

**Issue by anonimitoraf** [tumashu/vertico-posframe#13]
For example, I only want to use vertico-posframe when searching for files, not when searching for words/symbols. Is there any way to do this?

**Comment by tumashu** [comment]
try [vertico-multiform](https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category).

**Comment by anonimitoraf** [comment]
Cool thanks!

**Comment by anonimitoraf** [comment]
Actually, sorry to re-open

I tried
```
(setq vertico-multiform-commands
    '((execute-extended-command (lambda (&rest enabled?)
                                  (vertico-posframe--display 0)))))
```
but while it does seem to work, it has a massive delay and it expands the minibuffer too
![image](https://user-images.githubusercontent.com/15933322/156957829-719053da-94dd-47d6-be21-ded9357568f6.png)

I'm guessing I'm doing something wrong?

**Comment by tumashu** [comment]
;; Turn on vertico-posframe-mode on for M-x
(setq vertico-multiform-command-modes
      '((execute-extended-command posframe)))

**Comment by anonimitoraf** [comment]
Ah, perfect!
