### ISSUE TITLE
If my search gets really long, I can no longer see the candidates

### ISSUE THREAD

**Issue by draxil** [tumashu/vertico-posframe#14]
If my search gets too long for the posframe, the whole view aligns so I can no longer see the candidates:

![image](https://user-images.githubusercontent.com/44850/159131672-ef9179f8-f20f-4571-b3cd-efa82fc61175.png)

This doesn't happen in "vanilla" vertico as it just wraps:

![image](https://user-images.githubusercontent.com/44850/159131697-fb220275-57a4-442f-bfcd-286373b75877.png)

I feel like this is a recent thing, although maybe I've just started using longer paths.

**Comment by tumashu** [comment]
https://github.com/tumashu/vertico-posframe/commit/ef430c2a8a69939bd8b358670fe83fb3e75a4ffd

try (setq vertico-posframe-truncate-lines t)

**Comment by draxil** [comment]
Magic that fixes it for me! Thanks

**Comment by minad** [comment]
@tumashu I don't think the addition of `vertico-posframe-truncate-lines` is a good idea. You usually want truncation enabled and only disable it when the input becomes too long. See https://github.com/minad/vertico/blob/a92b1e47ffe343e2c3096e2ea61af013a8a02af9/vertico.el#L558 for how Vertico itself handles this. Maybe that automatic solution could work for vertico-posframe too?

**Comment by tumashu** [comment]
```
Maybe that automatic solution could work for vertico-posframe too?
```
Maybe :-)
