### ISSUE TITLE
Feature request: Per command posframe position like ivy-posframe

### ISSUE THREAD

**Issue by farazshaikh** [tumashu/vertico-posframe#24]
Ivy posframe position can be customized per command using the following

```
(setq ivy-posframe-display-functions-alist
          '((swiper-isearch  . ivy-posframe-display-at-window-bottom-left)
            (complete-symbol . ivy-posframe-display-at-point)
            (counsel-M-x     . ivy-posframe-display-at-point)
            (counsel-mark-ring . ivy-posframe-display-at-window-bottom-left)
            (ivy-switch-buffer . ivy-posframe-display-at-window-bottom-left)
            (t               . ivy-posframe-display-at-point)))
```

With the above feature vertico-posframe is very difficult to use, esp for commands like consult-line (swiper-eqivalent).
The posframe blocks the search results. 

It's ideal to sometimes have the posframe displayed at point, and sometimes at the bottom of the frame.

**Comment by tumashu** [comment]
maybe useful https://github.com/minad/vertico/blob/main/extensions/vertico-multiform.el

**Comment by farazshaikh** [comment]
Vertico multi form controls the layout vertico contents ie to display content as grid, vs a list.
It won't help to position the pos frame.   


At a minimum, there should be a way to disable posframe completely for certain command like vertico-line and display content in the mini buffer instead

**Comment by tumashu** [comment]
you can try the below config:

```
(setq vertico-multiform-commands
      '((consult-imenu buffer)
        (t posframe)))

(vertico-multiform-mode 1)

(setq vertico-posframe-poshandler
      #'my-vertico-posframe-poshandler)

(defun my-vertico-posframe-poshandler (info)
  (pcase this-command
    (`complete-symbol (posframe-poshandler-frame-top-center info))
    (`consult-line  (posframe-poshandler-frame-bottom-center info))
    (t  (posframe-poshandler-frame-center info))))

```

**Comment by farazshaikh** [comment]
With the above snippet, the consult-line posframe starts at the bottom center. 
But, as soon as you type anything, the posframe moves back to the center of the window.

Thanks
-Fs

**Comment by tumashu** [comment]
```
(setq vertico-multiform-commands
      '((consult-imenu buffer)
        (t posframe)))

(vertico-multiform-mode 1)

(setq vertico-posframe-poshandler
      #'my-vertico-posframe-poshandler)

(defun my-vertico-posframe-poshandler (info)
  (cond
   ((my-cmdp 'complete-symbol) (posframe-poshandler-frame-top-center info))
   ((my-cmdp `consult-line)  (posframe-poshandler-frame-bottom-center info))
   ((my-cmdp `consult-recent-file)  (posframe-poshandler-frame-bottom-center info))
   (t  (posframe-poshandler-frame-center info))))

(defun my-cmdp (cmd)
  (or (equal this-command cmd)
      (equal last-command cmd)))

```

**Comment by farazshaikh** [comment]
Same behavior, box moves to the center
![start](https://user-images.githubusercontent.com/2507850/208289997-3491a851-c918-43cc-876f-4df88ffe1098.png)
![end](https://user-images.githubusercontent.com/2507850/208290000-b11deee0-c1b0-4d5d-8262-757e1e8008a3.png)

**Comment by tumashu** [comment]
Update to newest code, and try:
```
(setq vertico-multiform-commands
      '((consult-line posframe (vertico-posframe-poshandler . posframe-poshandler-frame-top-center))
        (t buffer)))

```

**Comment by farazshaikh** [comment]
Thanks it works, I had to add the posframe position for default case. 

```
  (setq vertico-multiform-commands
        '((consult-line posframe (vertico-posframe-poshandler . posframe-poshandler-frame-bottom-center))
          (consult-buffer posframe (vertico-posframe-poshandler . posframe-poshandler-frame-bottom-center))
          (t posframe (vertico-posframe-poshandler . posframe-poshandler-point-bottom-left-corner))))
```
![2022-12-18_20-59um](https://user-images.githubusercontent.com/2507850/208352316-6fa3bb5e-fdb3-45c4-9a96-2e3689782dd7.png)
![2022-12-18_21-00](https://user-images.githubusercontent.com/2507850/208352318-8b0de1c4-151f-41f7-b0d1-4d4fe1129931.png)
![2022-12-18_21-02](https://user-images.githubusercontent.com/2507850/208352320-289764c3-8f47-4726-b8ae-1bbaa8541693.png)
![2022-12-18_21-02_1](https://user-images.githubusercontent.com/2507850/208352322-3b844b79-1106-4a35-a105-f55096299c46.png)

**Comment by tumashu** [comment]
ok
