### ISSUE TITLE
Avoid advices

### ISSUE THREAD

**Issue by minad** [tumashu/vertico-posframe#26]
In the next Vertico release you can use `cl-defmethod` to hook in more cleanly into Vertico. See https://github.com/minad/vertico/commit/2346498e6ae9e00947ac3ca6cad5def61df0ea24.

**Comment by tumashu** [comment]
If use cl-defmethod, I think vertico--resize-window should be renamed to vertico-resize-window, for it is public interface  now:-)

**Comment by minad** [comment]
No, it will stay internal.

**Comment by tumashu** [comment]
:)

**Comment by minad** [comment]
There is no reason to make these APIs public. It is only a cleaner technique to provide extension mode implementations.

**Comment by tumashu** [comment]
ok, I will wait new version of vertico :-)

**Comment by minad** [comment]
I've released a new version. See also https://github.com/minad/vertico/issues/331 which should help you with #29.

**Comment by tumashu** [comment]
Fixed.
