### ISSUE TITLE
Prompt flickers

### ISSUE THREAD

**Issue by minad** [tumashu/vertico-posframe#3]
Hey @tumashu,

I just tried vertico-posframe and it seems to work well, much better than last time I tried posframe! However I found that the prompt flickers if you scroll quickly through the candidate list of e.g. M-x. Then the prompt string "M-x" flickers noticeably. No other parts of the UI flicker, besides some initial flicker at startup. Any idea what could be causing this prompt flicker and if it is fixable? Thanks!

**Comment by tumashu** [comment]
please try last code, maybe fixed :-)

**Comment by minad** [comment]
The prompt flicker is indeed gone, but now the cursor flickers badly. Please compare with https://github.com/minad/mini-popup, which does not have the issue.

One more thing I'd like to point out - you can be a bit more economical with your usage of advices:

https://github.com/tumashu/vertico-posframe/blob/7134c809d4b8966f1cab7f4f3a0fc6757ff42d7d/vertico-posframe.el#L324-L329

Instead of advising `completing-read-default` and `completing-read-multiple` and obtaining the window you can use `minibuffer-selected-window`. So these two advices are unnecessary. Then you install another post-command-hook. This hook should not be necessary since you replace the display function. The display function is executed at the end of the `vertico--exhibit` post-command-hook. You can move the code of your `vertico-posframe--post-command-function` to your `vertico-posframe--display` function.

**Comment by tumashu** [comment]
```
minibuffer-selected-window
```
good idea.

**Comment by tumashu** [comment]
```
You can move the code of your vertico-posframe--post-command-function to your vertico-posframe--display function
```
done.

**Comment by tumashu** [comment]
```
but now the cursor flickers badly.
```
I think this should improve :-)

**Comment by minad** [comment]
Works pretty well now and also looks good code wise. Thanks!
