### ISSUE TITLE
Vertico-mode doesn't work as posframe fallback mode

### ISSUE THREAD

**Issue by bcmertz** [tumashu/vertico-posframe#30]
It seems that `vertico-mode` doesn't work as a `vertico-posframe-fallback-mode` in terminal

Using `vertico-buffer-mode` as shown in the documentation works perfectly as a fallback, but something like
```
(setq vertico-multiform-categories
    '((t posframe
       (vertico-posframe-fallback-mode . vertico-mode))))
```
defaults to the regular builtin non-vertical completion system. Is this intended behavior or might I be missing something? 

Thank you for the excellent package!

**Comment by tumashu** [comment]
it will not work, for vertico-posframe require vertico-mode enable
