### ISSUE TITLE
Fallback to normal vertical mode in the minibuffer when in the terminal.

### ISSUE THREAD

**Issue by WuuBoLin** [tumashu/vertico-posframe#36]
The section [how-to-let-vertico-posframe-work-well-with-vertico-multiform](https://github.com/tumashu/vertico-posframe?tab=readme-ov-file#how-to-let-vertico-posframe-work-well-with-vertico-multiform) in the README shows the example of setting `vertico-posframe-fallback-mode` to `vertico-buffer-mode`, but buffer mode is difficult to use and not suitable for most use case, any ways to set default **vertical mode** as fallback?

I had a [discussion](https://github.com/minad/vertico/discussions/408) on vertico's repo.

**Comment by tumashu** [comment]
Try to remove vertico-posframe-fallback-mode  line or (vertico-posframe-fallback-mode #'ignore)

**Comment by tumashu** [comment]
I try to fix this issue, please try it.

**Comment by WuuBoLin** [comment]
**IT WORKS!!** Thank you very much. I appreciate your work.
