### ISSUE TITLE
Disable per command

### ISSUE THREAD

**Issue by AloisJanicek** [tumashu/vertico-posframe#5]
It would be great to have a nice way to disable `vertico-posframe` on the per command basis, something like `ivy-posframe-display-functions-alist` of `ivy-posframe`.

For example I personally think that displaying `vertico` buffer of `consult-line` / `consult-grep` completion in posframe popup is distracting and I would like to have an easy way to tell `vertico-posframe` to ignore those particular commands.

**Comment by tumashu** [comment]
I think it does not have a simple way to do this job

**Comment by minad** [comment]
I just added [vertico-multiform](https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category). It should be possible to use this for `vertico-posframe`. There is no need to add something here.

~~~ elisp
;; Turn on vertico-posframe-mode on for M-x
(setq vertico-multiform-command-modes
      '((execute-extended-command posframe)))
~~~

**Comment by tumashu** [comment]
cool!

**Comment by AnabasisXu** [comment]
> For example I personally think that displaying `vertico` buffer of `consult-line` / `consult-grep` completion in posframe popup is distracting and I would like to have an easy way to tell `vertico-posframe` to ignore those particular commands.

Try this

```
	(vertico-multiform-mode 1)
	
	(defvar my-vertico-disable-posframe-commands
		'(consult-line consult-todo consult-ripgrep))

	(setq vertico-multiform-commands
				(append
				 (mapcar (lambda (cmd) `(,cmd (:not posframe))) ; 
								 my-vertico-disable-posframe-commands)
				 '((t posframe)))) ; 
```
