### ISSUE TITLE
How to change position to top center?

### ISSUE THREAD

**Issue by aminevsaziz** [tumashu/vertico-posframe#9]
Is in possible to change the position of the posframe to the top center? I don't see any function that help on achieving that

**Comment by tumashu** [comment]
can, use this

(defcustom vertico-posframe-poshandler #'posframe-poshandler-frame-center
  "The posframe poshandler used by vertico-posframe."
  :type 'function)

在 2022-01-09 21:39:35，"Merghadi Abdelaziz" ***@***.***> 写道：


Is in possible to change the position of the posframe to the top center? I don't see any function that help on achieving that

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aminevsaziz** [comment]
Then what? I mean its custom function but how to set the values for top center?

**Comment by tumashu** [comment]
set to posframe-poshandler-frame-top-center or posframe-poshandler-window-top-center

**Comment by aminevsaziz** [comment]
> set to posframe-poshandler-frame-top-center or posframe-poshandler-window-top-center

Unfortunately it didn't work at all. Those function do exist in ivy-posframe but not in the vertico.el. can you please add them so we can be able to change position.

**Comment by tumashu** [comment]
No, thay are in posframe package

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/148726783-2faeeb10-5fa3-4605-93bd-210dc0b41de9.png)

**Comment by aminevsaziz** [comment]
![Screenshot_20220110-074036_Chrome](https://user-images.githubusercontent.com/28719585/148726908-1bb45cba-c9f9-4a1d-99af-ae73d2c7896b.png)
![Screenshot_20220110-074016_Chrome](https://user-images.githubusercontent.com/28719585/148726913-64c9cb65-da2c-49bd-b5d6-cdcba076d639.png)

Take a look.

**Comment by aminevsaziz** [comment]
> ![图片](https://user-images.githubusercontent.com/67725/148726783-2faeeb10-5fa3-4605-93bd-210dc0b41de9.png)

What did you wrote there in the scratch? (setq posframe-poshandler-frame-top-center t) and (setq posframe-poshandler-window-top-center t) , am I write?

**Comment by tumashu** [comment]
posframe, not vertico-posframe

**Comment by aminevsaziz** [comment]
> posframe, not vertico-posframe

So I need to use posframe instead of vertico-posframe

**Comment by tumashu** [comment]
I mean the two functions is in posframe package,  vertico-posframe depend posframe, so you have installed posframe, just use them.

**Comment by tumashu** [comment]
(setq vertico-posframe-poshandler #'posframe-poshandler-frame-top-center)

**Comment by aminevsaziz** [comment]
> (setq vertico-posframe-poshandler #'posframe-poshandler-frame-top-center)

Thank you🎊. Everything work as it should be.

BTW, what does the # do. I mean the # before 'posframe-...etc

**Comment by tumashu** [comment]
#'xxx is shorthand of (function xxx)

在 2022-01-10 15:53:58，"Merghadi Abdelaziz" ***@***.***> 写道：


(setq vertico-posframe-poshandler #'posframe-poshandler-frame-top-center)

Thank you🎊. Everything work as it should be.

BTW, what does the # do. I mean the # before 'posframe-...etc

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
